### ISSUE TITLE
Bridge with Telegram Unixporn Group

### ISSUE THREAD

**Issue by heavyrain266** [unixporn/ideas#8]
I think special channel with bot-bridge with telegram group will be usefull because not every discord user uses the telegram and vice versa. Often a lot of people ask for help for example over such a bridge it would be easier to write back because there is more activity on discord.

**Comment by eepykate** [comment]
I think you misunderstood what this repo is for.

It's not for suggestions about unixporn (discord, reddit, etc), it's about dumping project ideas for/by the unixporn community.

Also the telegram group is unofficial and connecting them would just make us have to do extra work with little-to-no benefit.

**Comment by buffet** [comment]
Also the Telegram group doesn't always meet our moderation standards, so we'd have to "reform" it, optimally having some mods on their side as well.

As it stands I sometimes (rarely) wish it wouldn't use the unixporn name without talking to us first.

**Comment by heavyrain266** [comment]
oh, thanks for info and sorry, I will close this issuese

**Comment by eepykate** [comment]
github is confusing.

when i made my initial comment the 'delete issue' button was there, i'm not 100% sure about when i +1'd buffy's comment, but I think it was there too.

I wouldn't have deleted it ofc, but it's just weird how inconsistently it appears.
